### ISSUE TITLE
[dot rendering] repetitions on attribute, pipe split

### ISSUE THREAD

**Issue by zeph** [igordejanovic/textX#17]
when defining a value as a repetition like: `tag+=WORD['|']`
the resulting dot file has an unescaped pipe between the values, leading to a wrong rendering

p.s. I will try to fix this, I'm creating the issue here as I could not on my fork/github

**Comment by igordejanovic** [comment]
I can't reproduce this. The pipe from repetition modifier should not be used in dot rendering at all. This should convert to `tag: list[WORD]` in the dot.
Maybe you were having problems with the issue  #18 in your grammar?

**Comment by zeph** [comment]
you r right, my fault
