### ISSUE TITLE
[dot rendering] escape curly brackets in string of label

### ISSUE THREAD

**Issue by zeph** [igordejanovic/textX#18]
original `label="{WORD|[^*.#\[\]\\{\\}\,]+}"]`
aimed `label="{WORD|[^*.#\[\]\\\{\\\}\,]+}"]`

expected rendering on xdot `[^*.#\[\]\{\}\,]+`

actually... we need `label="{WORD|[^*.#\\[\\]\\\{\\\}\\,]+}"]` -> so, extra escaping 
on the slashes in front of the `[ ] , ` ...there is a general issue with the escaping

p.s. I will try to fix this, I'm creating the issue here as I could not on my fork/github

**Comment by igordejanovic** [comment]
Hi Guido, thanks for the report. I just made some simple fix in the exporter that should solve escaping problems. Could you test it?

**Comment by zeph** [comment]
@igordejanovic  absolutely! have u pushed a branch I can test?

**Comment by igordejanovic** [comment]
It is on the master.

**Comment by zeph** [comment]
awesome

**Comment by zeph** [comment]
yep, tested... that works like a charme

thanks :)

**Comment by igordejanovic** [comment]
Great :+1:
